### ISSUE TITLE
Add support for Europe

### ISSUE THREAD

**Issue by thet10** [dmgrstuff/launchcmoc#1]
As I am European this serves no purpose to me if it doesn’t include European support

**Comment by dmgrstuff** [comment]
I've been working on support for Europe and Japan, so as soon as I test it I'll include it in the next release.

**Comment by dmgrstuff** [comment]
Just released [v1.1](https://github.com/dmgrstuff/launchcmoc/releases/tag/v1.1), let me know if it works for you.

**Comment by dmgrstuff** [comment]
Closing this issue as it's been a while. If there's a problem, please open another issue, thanks!
